# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just the Class
tagline: A Jekyll template for course websites
description: A modern, highly customizable, responsive Jekyll template for course websites
author: Kevin Lin
baseurl: '/just-the-class' # the subpath of your site, e.g. /blog
url: 'https://kevinl.info' # the base hostname & protocol for your site, e.g. http://example.com
exclude: [
	 "Gemfile",
	 "Gemfile.lock",
	 "LICENSE",
	 "vendor",
	 "assets/revealjs/test",
	  "assets/revealjs/index.html",
    	  "assets/revealjs/README.md",
    	  "assets/revealjs/bower.json",
    	  "assets/revealjs/Gruntfile.js",
    	  "assets/revealjs/CONTRIBUTING.md",
    	  "assets/revealjs/LICENSE",
    	  "assets/revealjs/package.json",
	  "assets/revealjs/examples",
	  "assets/revealjs/css/theme/README.md",
	  "assets/revealjs/demo.html",
	 ]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.1
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Kevin Lin:
    - 'https://kevinl.info'
  Just the Class on GitHub:
    - 'https://github.com/kevinlin1/just-the-class'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  revealjs:
     search_exclude: true
     nav_exclude: true
 
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

markdown_slide_separator: ---
permalink: "/:title"
slideNumber:
  # Slide number formatting can be configured using these variables:
  #  "h.v":  horizontal . vertical slide number (default)
  #  "h/v":  horizontal / vertical slide number
  #    "c":  flattened slide number
  #  "c/t":  flattened slide number / total slides
  # "none":  dont't show slide numbers
  format: "c/t"
reveal_path: "assets/revealjs/"

## most values are unchanged from their defaults. The variables
## that are unchanged are commented out and their default value is shown with _val_
## for a full listing of values and defaults see https://revealjs.com/config/
reveal:
  theme: "white" # black/beige/blood/league/moon/night/serif/simple/sky/solarized/white
  ## The "normal" size of the presentation, aspect ratio will be preserved
  ## when the presentation is scaled to fit different resolutions. Can be
  ## specified using percentage units.
  width: 1200
  height: 960
  ## Factor of the display size that should remain empty around the content
  margin: 0.1
  ## Bounds for smallest/largest possible scale to apply to content
  minScale: 0.2
  maxScale: 1.5
  ## Add the current slide number to the URL hash so that reloading the
  ## page/copying the URL will return you to the same slide (true | _false_)
  hash: true ## must be true or fragments break
  ## Push each slide change to the browser history.  Implies `hash: true` (true | _false_)
  ## history: false


  ## Display presentation control arrows
  ## Show controls? (_true_ | false)  default values for all settings shown as _val_
  ## controls: true

  ## Help the user learn the controls by providing hints, for example by
  ## bouncing the down arrow when they first encounter a vertical slide (true | _false_)
  ## controlsTutorial: false 

  ## Disables the default revealjs slide layout (scaling and centering)
  ## so that you can use custom CSS layout (true | _false_)
  ## disableLayout: false

  ## The maximum number of pages a single slide can expand onto when printing
  ## to PDF, unlimited by default (Number.POSITIVE_INFINITY)
  ## pdfMaxPagesPerSlide: 100

  

